# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webapp-direto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webappteste100.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a3fa538ceb3344de8e61d2e2413c9afb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2f240d42383b4292a9b10a4d8aff5e4e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webappteste100.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a3fa538ceb3344de8e61d2e2413c9afb }}/teste:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp-direto'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4241cb8b54764ea0a806a9d1a1ae8068 }}
        images: 'webappteste100.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a3fa538ceb3344de8e61d2e2413c9afb }}/teste:${{ github.sha }}'